#include "khora/akoe/akoe.hpp"

#include <algorithm>
#include <cmath>

namespace khora::akoe {

namespace {

// One glyph per band and one per quantised level, drawn from fixed seeds so the
// same sound encodes to the same glyph in every process. The retina learned this
// the hard way: level glyphs generated by random bit flips COLLIDE, so the top
// and bottom of the range end up 0.25 similar when they must be 0. Levels here
// are built from a permutation instead, giving each level a disjoint block of
// bit positions, so level 0 and level max share nothing.
const std::vector<khora::lattice::Glyph>& band_glyphs(std::size_t n) {
    static std::vector<khora::lattice::Glyph> g;
    if (g.size() < n) {
        g.clear();
        for (std::size_t i = 0; i < n; ++i)
            g.push_back(khora::lattice::Glyph::random(0xA1C0DE00ull + i));
    }
    return g;
}

std::vector<khora::lattice::Glyph> make_levels(std::size_t levels) {
    // A graded scale: level k differs from level k+1 in one block of bits, so
    // similarity falls monotonically with distance in energy. Two levels that are
    // close should LOOK close, or a quiet band and a loud one become unrelated
    // symbols and no generalisation is possible.
    std::vector<khora::lattice::Glyph> out;
    out.reserve(levels);
    khora::lattice::Glyph base = khora::lattice::Glyph::random(0x5EA50000ull);
    const std::size_t dim = khora::lattice::kGlyphBits;
    const std::size_t block = dim / std::max<std::size_t>(levels, 1);
    for (std::size_t k = 0; k < levels; ++k) {
        khora::lattice::Glyph g = base;
        // Flip the first k blocks. Level 0 is base; level max differs in every
        // block, so the two ends are maximally apart and everything in between
        // is graded.
        for (std::size_t b = 0; b < k; ++b)
            for (std::size_t i = b * block; i < (b + 1) * block && i < dim; ++i)
                g.flip_bit(i);
        out.push_back(g);
    }
    return out;
}

const std::vector<khora::lattice::Glyph>& level_glyphs(std::size_t n) {
    static std::vector<khora::lattice::Glyph> g;
    static std::size_t cached = 0;
    if (cached != n) { g = make_levels(n); cached = n; }
    return g;
}

} // namespace

Ear::Ear(std::size_t bands, std::size_t levels, double lo, double hi,
         std::size_t frame_samples)
    : bands_(std::max<std::size_t>(bands, 1)),
      levels_(std::max<std::size_t>(levels, 2)),
      frame_(std::max<std::size_t>(frame_samples, 16)),
      lo_(lo), hi_(hi) {}

Spectrogram Ear::analyse(const Sound& s) const {
    Spectrogram sp;
    if (s.samples.empty()) return sp;
    sp.bands  = bands_;
    sp.frames = s.samples.size() / frame_;
    if (sp.frames == 0) { sp.frames = 1; }
    sp.energy.assign(sp.frames * sp.bands, 0.0);

    // Logarithmic band centres. Pitch is perceived logarithmically, and linear
    // spacing would put most of the channels above 3 kHz where almost nothing
    // that matters lives.
    std::vector<double> centre(bands_);
    const double ratio = std::pow(hi_ / lo_, 1.0 / static_cast<double>(std::max<std::size_t>(bands_ - 1, 1)));
    double f = lo_;
    for (std::size_t b = 0; b < bands_; ++b) { centre[b] = f; f *= ratio; }

    // A naive DFT at each band centre -- one complex accumulator per band, not a
    // full FFT. That is O(frame * bands) rather than O(frame log frame), and for
    // 512-sample frames and 24 bands it is a few hundred thousand multiply-adds
    // per second of audio, which is nothing. An FFT here would be a page of index
    // arithmetic needing its own test to be trustworthy, for a speedup nothing is
    // waiting on.
    for (std::size_t fr = 0; fr < sp.frames; ++fr) {
        const std::size_t start = fr * frame_;
        const std::size_t n = std::min(frame_, s.samples.size() - std::min(start, s.samples.size()));
        double peak = 0.0;
        for (std::size_t b = 0; b < bands_; ++b) {
            const double w = 2.0 * 3.14159265358979323846 * centre[b] / s.rate;
            double re = 0.0, im = 0.0;
            for (std::size_t i = 0; i < n; ++i) {
                // A Hann window, because a rectangular one smears every tone
                // across every band and would make the whole spectrogram mush.
                const double win = 0.5 - 0.5 * std::cos(2.0 * 3.14159265358979323846
                                    * static_cast<double>(i) / static_cast<double>(std::max<std::size_t>(n - 1, 1)));
                const double x = s.samples[start + i] * win;
                re += x * std::cos(w * static_cast<double>(i));
                im -= x * std::sin(w * static_cast<double>(i));
            }
            const double mag = std::sqrt(re * re + im * im) / static_cast<double>(std::max<std::size_t>(n, 1));
            sp.energy[fr * bands_ + b] = mag;
            peak = std::max(peak, mag);
        }
        // Per-frame normalisation, so a quiet recording and a loud one of the
        // same sound encode alike. Absolute level is a property of the
        // microphone, not of what was said.
        if (peak > 0.0)
            for (std::size_t b = 0; b < bands_; ++b) sp.energy[fr * bands_ + b] /= peak;
    }
    return sp;
}

khora::lattice::Glyph Ear::encode(const Sound& s) const {
    return encode(analyse(s));
}

khora::lattice::Glyph Ear::encode(const Spectrogram& sp) const {
    if (sp.frames == 0 || sp.bands == 0) return khora::lattice::Glyph::zero();
    const auto& bg = band_glyphs(sp.bands);
    const auto& lg = level_glyphs(levels_);

    std::vector<khora::lattice::Glyph> frames;
    frames.reserve(sp.frames);
    for (std::size_t fr = 0; fr < sp.frames; ++fr) {
        std::vector<khora::lattice::Glyph> cells;
        cells.reserve(sp.bands);
        for (std::size_t b = 0; b < sp.bands; ++b) {
            const double e = std::clamp(sp.at(fr, b), 0.0, 1.0);
            const std::size_t lv = std::min(levels_ - 1,
                static_cast<std::size_t>(e * static_cast<double>(levels_)));
            // SILENCE CONTRIBUTES NOTHING, and leaving it in was costing most of
            // the representation. A band at level 0 is a band with nothing in it,
            // and binding a glyph for it means every sound shares a term with
            // every other sound wherever both are quiet -- which is most bands,
            // most of the time. Measured on 60 chords, two UNRELATED sounds came
            // out 0.484 similar while two unrelated words are 0.002 apart, and
            // that baseline is subtracted from every margin the memory has to
            // work with. An empty band is now simply absent from the bundle.
            if (lv == 0) continue;
            cells.push_back(khora::lattice::bind(bg[b], lg[lv]));
        }
        if (cells.empty()) continue;   // a silent frame is not a frame
        // PERMUTE BY FRAME INDEX. Bundling is commutative, so without this a
        // rising tone and a falling one bundle to the same glyph -- the
        // representation would be a bag of frames with no time in it at all.
        frames.push_back(khora::lattice::permute(
            khora::lattice::bundle(std::span<const khora::lattice::Glyph>(cells)),
            static_cast<int>(fr)));
    }
    return khora::lattice::bundle(std::span<const khora::lattice::Glyph>(frames));
}

void Listener::learn(const khora::lattice::Glyph& g, int label) {
    for (std::size_t i = 0; i < labels_.size(); ++i) {
        if (labels_[i] == label) { examples_[i].push_back(g); rebuild_(i); return; }
    }
    labels_.push_back(label);
    examples_.push_back({g});
    protos_.push_back(g);
}

void Listener::rebuild_(std::size_t i) {
    protos_[i] = khora::lattice::bundle(
        std::span<const khora::lattice::Glyph>(examples_[i]));
}

std::pair<int, double> Listener::classify(const khora::lattice::Glyph& g) const {
    int best = -1;
    double best_sim = -2.0;
    for (std::size_t i = 0; i < protos_.size(); ++i) {
        const double s = g.similarity(protos_[i]);
        if (s > best_sim) { best_sim = s; best = labels_[i]; }
    }
    return {best, best < 0 ? 0.0 : best_sim};
}

} // namespace khora::akoe
